services:
  # Full Stack App (Backend serving Frontend)
  - type: web
    name: qr-restaurant-app
    env: node
    buildCommand: npm install --include=dev && npm run build && cd backend && npm install --include=dev && npm run build && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: FRONTEND_URL
        value: "https://qr-restaurant-app.onrender.com"
      - key: WEBPAY_COMMERCE_CODE
        sync: false
      - key: WEBPAY_API_KEY
        sync: false
      - key: WEBPAY_ENVIRONMENT
        value: "integration"